### ISSUE TITLE
cant import 

### ISSUE THREAD

**Issue by Alaaeldinn** [autodistill/autodistill-yolo-world#1]
can't import yolo-world model , just change this **from autodistill_yolo_world.yolo_world_model import YOLOWorld** in init file to from **autodistill_yolo_world.yolo_world_model import YOLOWorldModel** , or change the name of the class plz @capjamesg

**Comment by capjamesg** [comment]
Hello @Alaaeldinn! Thank you for your interest in Autodistill! Please run `pip install --upgrade autodistill-yolo-world` and try again. We just (a few minutes ago!) published the first version of Autodistill YOLO World that is ready for use.

Let me know if you run into any problems!
